export const CANVAS_LAYOUT = {
  WIDTH: 400,
  HEIGHT: 400,
  NUM_COL: 80,
  NUM_ROW: 80,
};

export const CELL_LAYOUT = {
  CELL_HEIGHT: CANVAS_LAYOUT.HEIGHT / CANVAS_LAYOUT.NUM_COL,
  CELL_WIDTH: CANVAS_LAYOUT.WIDTH / CANVAS_LAYOUT.NUM_ROW,
};

export const FILL_PERCENT = 0.9;
